### ISSUE TITLE
Visualizing buckets and rivers

### ISSUE THREAD

**Issue by ekala** [ushahidi/SwiftRiver#1]
Building the visualizations (maps, graphs, word clouds etc) for the buckets and rivers based on the droplet metadata (tags, links, place names etc)

**Comment by 69mb** [comment]
Issues #15 #16 #17 #18 #19 created to track individual completion of each visualization.

**Comment by dkobia** [comment]
Ideally we should hold off on visualization until rivers, streams, buckets and droplet views are complete since visualizations are plugins and not core elements.

**Comment by ekala** [comment]
Closing this out - river/stream and bucket view are complete
