### ISSUE TITLE
Adding twitter keyword doesn't appear until refresh

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/SwiftRiver#101]
1. Create a new river
2. Goto river settings
3. Type 'html5' into twitter keyword box
4. Click 'Add'
   ... Nothing happens
5. Refresh page and keywords now appear

Behaviour is confusing as there is no feedback to the user at all, I accidentally added the same keyword 5 times trying to work out what was happening.
Same issue with RSS.

**Comment by ekala** [comment]
The keyword actually appears but you need to give it some time if you're on a slow connection. We're working on speeding up these kinds of simple operations.

**Comment by 69mb** [comment]
Actually the MQ was down with the memory issues, that's fixed but we also need the river settings to provide visual feedback... show the loading icon during the ajax call and flash and error/success message.

**Comment by ekala** [comment]
Further investigation reveals that it's the PHP-FCGI configuration on the LAMP stack. The logs show a "premature end of script headers" error

**Comment by ekala** [comment]
Server-side issue. Fixed
