### ISSUE TITLE
change password not functioning

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/SwiftRiver#102]
On the login screen, when I  click "Forgot your RiverID password?" the box for the email address appears, but won't let you add your email address.

Behaviour:
Click " Forgot your RiverID password?" 
the Email address field appears
click below to enter email address
field disappears
User is stuck and unable to change password.

Thanks

**Comment by 69mb** [comment]
Fixed with d0311a555050aad3fa177279c0114baeaabe2245
