### ISSUE TITLE
Expire Rivers

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#104]
Disable a river after [X] days or weeks of inactivity. 1 week for now, we'll tune this later.

**Comment by dkobia** [comment]
I think we should indicate that a River has gone inactive and 'Click here to reactivate' -- adding @brandonrosage

**Comment by ekala** [comment]
This feature will require background maintenance jobs. Additionally, the channel filter options for the expired rivers shall have to be removed from the RSS, Twitter etc crawling schedule

Also, a notification to the user (via email and dashboard) that their river has expired?

**Comment by 69mb** [comment]
Think the expiry date should be extended by another 14 days if an owner accesses a river before it expires but we will limit the view of the river to 14 days of drops.

This way we don't hustle active users with expiry constantly, limit how much data we need to maintain for a river and if they abandon their river then it shuts down.

**Comment by ekala** [comment]
In which case we need to set a watermark for the time when we automatically extend the expiry date? i.e. if accessed x days to expiry, extend the expiry date.

As for limiting the view to 14 days, I presume this applies to all users irrespective of how far off the expiry date is
