### ISSUE TITLE
Pre-compute trend and dashboard data

### ISSUE THREAD

**Issue by ekala** [ushahidi/SwiftRiver#109]
The data used to generate trends needs to be pre-computed and cached to avoid hitting up the DB. The cache ought to be refreshed based on a defined schedule e.g. every 15 minutes.

**Comment by dkobia** [comment]
I think this comes back to the issue of:
- Allowing trends to define their specific queries
- Queuing those queries somehow and caching them every X minutes?

**Comment by ekala** [comment]
Pre-computation also feeds into #116

**Comment by 69mb** [comment]
Closed by 3bc65e36
