### ISSUE TITLE
Droplet Display

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#11]
- Users can comment on droplets("Droplet Related Discussion")
- Add tags to a droplet in addition to those created by the automatic semantic analysis
- Add attachments to a droplet

**Comment by 69mb** [comment]
- Thoughts on how to delete tags,links,places that have beed added in line? Thinking we do this through a popup menu.
- How to make meta added via automatic semantic tagging editable given a droplet is shared by across rivers.

**Comment by ekala** [comment]
@brandonrosage Any chance you've worked on some mockups for this feature - i.e. the UI for a user to add/remove a tag, attach a media item, attachment etc
