### ISSUE TITLE
User Dashboard

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#116]
The new user dashboard removes the separate pages for rivers and buckets which are not panels on the dashboard page on the right.

Also adds a popular rivers and buckets display for surfacing rivers + buckets system wide.

![](http://dl.dropbox.com/u/48291217/Screenshots/lfmo.png)

**Comment by ekala** [comment]
Closed in f896eec41d57569d5a5b0454994e9464656faebc
