### ISSUE TITLE
Missing Stalkers UI

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#117]
The new UI is missing something similar to the followers/following UI from before:
![](http://dl.dropbox.com/u/48291217/Screenshots/hole.png)

**Comment by brandonrosage** [comment]
I've included this pattern in both [the dashboard template](https://github.com/ushahidi/Swiftriver_v2/blob/refresh/markup/index.php#L20-37) and [the pattern portfolio](https://github.com/ushahidi/Swiftriver_v2/blob/refresh/markup/patterns.php#L172-193).

I'm not entirely sold on it, as it strikes me as too much noise. But with some feedback, we can iterate.
