### ISSUE TITLE
Account settings page

### ISSUE THREAD

**Issue by ekala** [ushahidi/SwiftRiver#124]
Implement the new account settings page.

__this page needs a save button and to prompt for the current password when saving__

![](http://dl.dropbox.com/u/48291217/Screenshots/gfls.png)

**Comment by brandonrosage** [comment]
The prototype for this save button is included in today's commit (https://github.com/ushahidi/Swiftriver_v2/commit/c95c3c2cd9a0e156e744587878d18bf48a9f6f2e), within /markup/user/settings.php, as well as the more general "Pattern portfolio" in /markup/patterns.php
