### ISSUE TITLE
Default Avatar

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#131]
We need a default avatar for identities that are missing one ala the FB default silhouette below or the github octocat shadow ![](http://dl.dropbox.com/u/48291217/Screenshots/y0o3.png)

![](http://dl.dropbox.com/u/48291217/Screenshots/xwpd.png)

**Comment by brandonrosage** [comment]
I added a custom default avatar in today's commit: https://github.com/ushahidi/Swiftriver_v2/blob/refresh/themes/default/media/img/content/avatar_default.gif
