### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#158]
Add an entry in the popup menu to take the user to notifications, when the notification bubble is shown on the avatar. Otherwise its confusing what the notification is.

![](http://o7.no/IfNUxm)

**Comment by 69mb** [comment]
Also send add email notifications configurable in the account settings page for when a user gets a new follower, subscriber.

**Comment by ekala** [comment]
Perhaps we can have the notifications showing up in a drop down div so that the user doesn't have to go to their dashboard in order to view/accept/reject them

**Comment by 69mb** [comment]
Closed by a76597c
