### ISSUE TITLE
Rename 'River Channels' to 'River Filters'

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#161]
Feedback from Patrick: "I would use the word "Filters" instead of "Channels", far far more intuitive"

Brian: Not convinced but try it out and see if it works.

**Comment by brandonrosage** [comment]
Wouldn't this leave us with two different "Filters" functions? One for the data sources (e.g. Twitter, RSS) and another for the metadata (e.g. date, tags)?

**Comment by 69mb** [comment]
Yeah, can't think of any other way to distinguish the two. Think what we have currently works.
