### ISSUE TITLE
"Next" and "Previous" buttons in the drop dialog

### ISSUE THREAD

**Issue by ekala** [ushahidi/SwiftRiver#166]
When on a drop, it'd be great if I could just rate it, add tags, etc, and then click "next" - http://dl.dropbox.com/u/450917/Screenshots/0y.png

**Comment by nlewis2142** [comment]
"Next" and "Last" or "Previous" and "Next"?

**Comment by 69mb** [comment]
Doable purely in JS actually. The backbone collection is a sorted set and making a linked list out of it for this should be trivial.

**Comment by 69mb** [comment]
@Deathshiver yeah previous and next navigation.
