### ISSUE TITLE
Implement CrowdmapID API Key (Time Sensitive)

### ISSUE THREAD

**Issue by evansims** [ushahidi/SwiftRiver#173]
This coming week CrowdmapID will be switching to a new build that requires services pass an API key with requests. It's important this key is in place or any authentication calls after the switchover will fail.

All that is required is a "_api_secret_" parameter be passed along with calls to the service. The value of this parameter should be Swift's API key. I've provided @ekala with said key, but [it's also available here.](https://docs.google.com/a/ushahidi.com/document/d/1Oq_3hk2ezkpsoq8MJe-vc7onhPAVGkbWMXqd27zSmxY/edit)

**https://gist.github.com/aefc3bda341c44b033a3** includes modifications to _modules / riverid / classes / riverid / api.php_ and _application / config / auth.php.template_ that should contain all the necessary changes, but I do not have a local Swift installation available to test these tweaks.

Please let me know if you have any questions. Pinging @69mb and @dkobia just to be thorough.

**Comment by 69mb** [comment]
Your changes work ok and will put it up asap.

**Comment by 69mb** [comment]
Done in 0d44d630
