### ISSUE TITLE
Bucket RSS Feed

### ISSUE THREAD

**Issue by ekala** [ushahidi/SwiftRiver#174]
An RSS feed of the drops within a bucket. 

The bucket is the focal collaboration point - where the hand-picked items of interest reside so this is the content we should allow users to share. 

We could also extend the same concept to sharing the bucket in a newsletter/digest fashion.

**Comment by nlewis2142** [comment]
Basic RSS feed implementation added in b3576a2d3529837e1481be970ef813e106e1a74e @ branch rss-dev. Correctly working so far, but lacks an RSS button on the bucket page and needs some minor code cleanup. Action to view is /rss (e.g. http://swiftriver.beta/default/river/my-river/rss). Already verified the RSS output to be valid RSS2 standard.

Planning to go ahead and add Atom feed support while I'm doing this, shouldn't be too much harder.
