### ISSUE TITLE
Design: River List View - Thumbs Up/Down

### ISSUE THREAD

**Issue by nlewis2142** [ushahidi/SwiftRiver#176]
Stylistic issue after clicking thumbs up or down:

https://lh4.googleusercontent.com/-Dn7TjZKsP_4/T97QvM5p_0I/AAAAAAAAAAY/ciViWObJjRU/s720/1340002490064.png

**Comment by dkobia** [comment]
Tagging @brandonrosage  on this.

**Comment by nlewis2142** [comment]
Mis-reference
