### ISSUE TITLE
Start using and cataloguing stop words

### ISSUE THREAD

**Issue by dkobia** [ushahidi/SwiftRiver#178]
In order to prevent wasteful twitter firehose searches, we should start ignoring certain words (stop words). Here is a list that we can start with -- http://www.webconfs.com/stop-words.php

Beyond this admins should be able to add items like 'justin bieber' 'kardashian' etc etc. We don't need to fill our DB's with junk!!

**Comment by ekala** [comment]
Pointers on how to implement filter matching algorithms a al AdBlock Plus: http://adblockplus.org/blog/investigating-filter-matching-algorithms

**Comment by nlewis2142** [comment]
From what I understand, that's useful for matching keywords that can potentially be part of other words, but I believe in PHP we can take a much more efficient approach since each stop word is guaranteed to be an entire word (as opposed to a word-part). (eg. 'the' is only a stop word if it is its own word).

```
/**
 * FilterStopWords
 * @param   $stops  array   Set of stop words in array format
 * @param   $input  string  String of word(s) to check
 * @return          string  String with the stop words filtered out
 */
function FilterStopWords($stops, $input)
{
    $input = explode(' ', $input);
    foreach ($input as $key => $value)
    {
        if (in_array($value, $stops))
            unset($input[$key]);
    }
    return implode(' ', $input);
}

echo FilterStopWords(array('word1','word3'), "word1 word2 word3 word4 word5");
```

It can be modified to just give an error (boolean) as well if stop words are found.

**Comment by dkobia** [comment]
If I'm not wrong, I think twitter allows for quote enclosed phrases, so we need to make sure those are not filtered out too?

**Comment by nlewis2142** [comment]
Will all the phrases be quoted then? The following should split by quote-enclosed w/ commas and then trim off the outer quotes that don't count as separation.

```
$input = explode("','", trim($input, "'"));
```

Edit: Tested and working

```
function FilterStopWords($stops, $input)
{
    $input = explode("','", trim($input, "'"));
    foreach ($input as $key => $value)
    {
        if (in_array($value, $stops))
            unset($input[$key]);
    }
    return implode(' ', $input);
}

echo FilterStopWords(array('word1','word3 - 4'), "'word1','word2','word3 - 4','word4','word5'");
```

Another solution would be to convert spaces into "+" for storage like many sites do, though the code can be adjusted to work either way.

**Comment by dkobia** [comment]
@Deathshiver -- the **str_getcsv** function actually handles both quoted and unquoted items, vs using explode :)

**Comment by dkobia** [comment]
Finally, I found a stop word list here that's pretty comprehensive -- http://www.twithawk.com/faq/stopwords
