### ISSUE TITLE
Bucket RSS + Permissions

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#180]
A buckets's feed is not accessible outside the browser session and for private deployments and buckets. 

Create a token url that will only allow access(make use of auth_tokens) to the bucket feed. Similar to having the logged in user's api_key in the url will allow access but the api_key is sensitive and should not be shared this way...

**Comment by ekala** [comment]
Some thoughts:
- Bucket RSS feeds can be added as feed URLs (when adding channel options for a river). Perhaps we should prevent this because in as much as the duplicity check will net the drops, we'll still have burnt CPU cycles (media extraction, semantic tagging)
- How about disabling the bucket rss feed when the deployment is private?

**Comment by nlewis2142** [comment]
I'm fine with making auth tokens, but where would we display this to the user? Are the auth tokens per-user or per-bucket? Does each user get an auth token or does only the bucket owner (who must give it to his users to let them see the bucket)? Where can the user reset the auth token if it is "stolen" (Bucket settings maybe)?

We should modify the RSS plugin to not accept feeds from it's own domain.

**Comment by 69mb** [comment]
The token should be per bucket and only applies to private buckets or any bucket's in a private deployment.

I think having a bucket feeding a river is an interesting use case. Maybe the droplet hash function could be improved so that the original drop could simple be placed into the river instead of being duplicated but given that drops have to be manually placed in the bucket, the volumes should be small enough not to warrant blocking this.

**Comment by nlewis2142** [comment]
I agree. As per the skype conversation I had earlier with @ekala, I think it could be a pretty good idea. I can see where he's coming from though which means the duplicate check would have to occur at the first stage.
