### ISSUE TITLE
Allow any user to invite

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#181]
- Add a setting to control if general invites are allowed in the deployment
- Up to a certain limit. Add a column num_invites to the users table for the number of invites a user can send and decremented every time one is sent.
- Default this to field to 10, we could script incrementing this to step load swiftriver.io?
- Integrate with gmail/yahoo/live

**Comment by nlewis2142** [comment]
Off-topic, but an interesting idea all the same:

We had discussed some about trying to incentivize users to help the community by posting comments and such. On private deployments, we could offer an option to allow additional invites based on activity as an incentive.

On public deployments we could use invites as a referral service which could be rewarded by something else.

Ultimately, the system seems to work better when you have more people looking at the same content, correct? This should get current users looking at more as well as increase the amount of future users. It would be disable-able in the settings.

**Comment by 69mb** [comment]
+1 on incentives for referrals. We will have limits on no of rivers, keywords, drops in a river on swiftriver.io and upping those limits could be a good reward.
