### ISSUE TITLE
Adding RSS Feed Failed

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/SwiftRiver#182]
I had to try three times to add an RSS feed to a new river. River name is Korean Language, here's a screen of the addition:

<a href="http://cl.ly/3g2O0y2w1u08331K3k3J"><img src="http://f.cl.ly/items/1H0z313h142R0E0Q3W0A/Screen%20Shot%202012-06-21%20at%204.07.45%20PM.png" /></a>

It worked the third time.

**Comment by brianherbert** [comment]
This is also happening with Twitter keywords:

<a href="http://cl.ly/0P3w3k073g1e1L2e3g1f"><img src="http://f.cl.ly/items/2e0D011G292W1b0s3p0c/Screen%20Shot%202012-06-21%20at%204.35.17%20PM.png"></a>

EDIT: When I hit enter to try again, the field said it was saving and then just disappeared.

**Comment by 69mb** [comment]
Could you try this again. There was a DB issue on swiftriver.io

**Comment by brianherbert** [comment]
Looking good!

**Comment by 69mb** [comment]
k thanks.
