### ISSUE TITLE
Created River Not Showing Up In Rivers List

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/SwiftRiver#183]
<a href="http://cl.ly/3s1N0W0E0G0W2B380c1h"><img src="http://f.cl.ly/items/2G1I3H3Y3w312c0F462G/Screen%20Shot%202012-06-21%20at%204.12.40%20PM.png"></a>

"Korean Language" should be showing up in that list since I just created it, but it's not there.

**Comment by 69mb** [comment]
Ditto on swiftriver.io

**Comment by brianherbert** [comment]
Seems good now.
