### ISSUE TITLE
Attempting to add Twitter as a channel does nothing

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/SwiftRiver#184]
<a href="http://cl.ly/3L3N0t1D0N0N22111M1q"><img src="http://f.cl.ly/items/1Q143N3d0h3J3p3m1h46/Screen%20Shot%202012-06-21%20at%204.31.41%20PM.png"></a>

When I click on the Twitter checkbox, I see a "Please wait, adding channel" in the background. It then goes away and nothing happens. I've tried repeatedly (maybe 5 or 6 times) and eventually two Twitter boxes popped up.

**Comment by 69mb** [comment]
Ditto on swiftriver.io

**Comment by brianherbert** [comment]
Thumbs up
