### ISSUE TITLE
When creating a River, skipping to step 3 (view) and then back to 2 starts you over

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/SwiftRiver#185]
After I named my River, I was presented with the add channels screen. I entered details for Twitter keywords, hit the "3. View your river" link, then clicked on "2. Open channels" which then forwarded me to step 1, "Name your river" which was blank.

I attempted to name my river "Korean Food" again and start over, but I was told it already existed. I checked to see if the River was in my list of rivers and it was not. It's out there in the void somewhere.

<a href="http://cl.ly/3F3o1r263o1g472o2m16"><img src="http://f.cl.ly/items/1p3U3T070v0T1T0t2b41/Screen%20Shot%202012-06-21%20at%204.41.10%20PM.png"></a>

**Comment by 69mb** [comment]
Ditto on swiftriver.io

**Comment by brianherbert** [comment]
Good to close this out.
