### ISSUE TITLE
Support UTF-8 Twitter Parameters

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/SwiftRiver#187]
ie. 삼겹살 should turn up plenty of results but doesn't.

**Comment by ekala** [comment]
The fix for ushahidi/SwiftRiver-Core#13 (referenced above) resolved this issue.

Closing.

**Comment by ekala** [comment]
The fix for ushahidi/SwiftRiver-Core#13 (referenced above) resolved this issue.
