### ISSUE TITLE
Second-level filtering mechanism

### ISSUE THREAD

**Issue by ekala** [ushahidi/SwiftRiver#188]
For some rivers, the drops are simply too many for a group of individuals to go through each one and place the relevant ones in their respective buckets. This is where a second-level filtering mechanism on the river comes in. 

Ideally, this filter would allow users to "auto-bucketize" drops if they meet the parameters specified in the filter. The filter should allow ANDing and/or ORing of the following parameters:
- Location (perhaps a geo-fence of sorts)
- Time
- Tags (people, organizations)
- Topics - see https://github.com/ushahidi/SwiftRiver-Tagger/issues/1

This mechanism would also provide a way of rating the parameter combination i.e. say out of the x drops that have flowed into the river, the 2nd level filter is only able to auto-bucketize y; rating is therefore `y/x * 100`. We would also have to track how a drop got into a bucket (manually or automatically) so that we can adjust the rating accordingly whenever a drop is added/removed from a bucket that's making use of this feature.

So in addition to the current workflow, collaboration at the river level would include tuning the parameters for the second-level filter i.e. calibrating the signal/noise ratio 

**NOTE** Because of the possibly high computational intensity of this feature, we would have to limit the no. of buckets that a user can use with this filter.

**Comment by dkobia** [comment]
This also comes back to the question of whether filter creation should be done in a modal window or separate page, where much more powerful functions can have much more room to be expressed in the UI

**Comment by nlewis2142** [comment]
Where will the settings for this "auto-bucketize" exist? Should the bucket have a filter page of sorts or should we classify them as an entirely separate class of buckets?

i.e. users can create normal buckets and such, but have the ability to promote a max of X buckets at a time to a "special bucket". (We could name it a tub :) ) Once promoted, the bucket would have additional pages in its settings menu. The limit could work similar to the way GitHub limits private repos: https://lh4.googleusercontent.com/-ZnklhNColw8/T-MRiKBcizI/AAAAAAAAAAw/-eW0TbSg3-A/s576/1340281223955.png

Envisioning it something like this: (Thank you Chrome Dev Tools): https://lh4.googleusercontent.com/-Op3RPUA4v-Y/T-MT1M2sTrI/AAAAAAAAAA4/ndGrdsscpps/s576/1340281802971.png

Of course, then do we still classify it as a bucket for the purpose of categorizing?

**Comment by ekala** [comment]
The "auto-bucketize" stuff would be on the river settings page so that as you set up the parameter combination, you specify the bucket the drops are to be placed in; if the bucket doesn't exist, it's created. Basically, the user shall be telling the system "for any new drops that has properties x, y and z place them in bucket a".

Also, the "auto-bucketize" parameters would only apply to incoming content

**Comment by brianherbert** [comment]
This is a brilliant idea and starts to solve the problem we had in Ushahidi in the first place. Currently, you still have to wade through all of the messages but this would allow you to essentially auto assign people / teams content to curate.

Also, this could be a paid feature, or the number of buckets you're allowed to auto dump drops into could be changed for paid users.

**Comment by nlewis2142** [comment]
Might as well just make this very similar to GitHub's private repo system (minus the public vs private part)
- Paying gives you access to this "upgraded" bucket
- The plan you choose decides how many you get
- Buckets can be freely upgraded or downgraded to use this feature, so you can change which bucket you are using it on at any time.
- "Upgraded" buckets can specify multiple rivers to pull from.
- Do we tell users this bucket is currently automatically finding content? ("This bucket is automatically finding relevant content. Click here to find out how.")
- Should advanced filters like #197 @brianherbert be only available to these sort of "upgraded" buckets? (More incentive to pay)
- Can users upgrade their plan in other ways than payment (contribution/collaboration)?

<img src="https://lh4.googleusercontent.com/-ZnklhNColw8/T-MRiKBcizI/AAAAAAAAAAw/-eW0TbSg3-A/s576/1340281223955.png" />
<img src="https://lh3.googleusercontent.com/-47c8BPgU9JQ/T-QwvyDb5BI/AAAAAAAAACA/aM5_RhOkuAA/s720/1340354750776.png" />

**Comment by 69mb** [comment]
This filter is very much needed especially for the junk that is a twitter stream. However, the result of the filter is not a bucket but still a much more focused river that solves the problem of individuals having to rummage through thousands of drops to find 1 good piece of info. 

We should not lose the single most valuable asset in swift i.e. buckets which are super curated buckets of information and neither should we abandon the most powerful filter in the form of the individual and the crowd. We do not have automated ways of doing this without diluting core swift aspects. 

Basically the way I see this working is:
- Step one to creating a river is opening the channels as we do now. 
- Then define this second level river filter by defining the keywords, locations, tags... to be picked from those channels.
- Et voila, the river begins flowing
- A mechanism to tune the filter further by saying remove drops like this would be nice. 

On the core we can handle this. The dropqueue and metadata extraction will change into a pipeline as follows:
-  Drop comes in as usual from twitter, rss, Ushahidi, smssync. 
- The drop queue processor will pass the drop to a preprocessing pipeline where the output of one processor is the input of the next. Here we will start with Adblock which will output into readability and preprocessing is done..
- Next the drop queue will take the drop to metadata processing which happens in parrallel as it does now. The drop queue will wait for all meta extractors to finish.
- Finally the drop queue processor will pass the drop for post processing where we will apply this filter. The processor for this will examine a drop and the river it's destined vs it's filter and either leave it destined for the river or filter it out

This should be included in this beta and the ui end @brandonrosage portfolio has everything we need.

Thoughts?

**Comment by ekala** [comment]
The pipeline looks good. A note on item 2; the AdBlock step may be unnecessary because readability will (almost always) strip out the ad content.

**Comment by ekala** [comment]
@brandonrosage I need some help with the UI for the river filters. We're looking at a scenario where a user can create a set of of one or more named filters where each set is a combination of location, tags, phrases/keywords etc. 

In the current beta for this feature, a user can only specify the filters via the river settings page but it would be nice to present this facility to the user during river creation - #137

**Comment by brandonrosage** [comment]
[My pull request today](https://github.com/ushahidi/SwiftRiver/pull/266) includes the frontend work on the "Flow" view that addresses complex filter and channel management on rivers.

**Comment by ekala** [comment]
This was addressed by the rules feature in #316.

Closing.
