### ISSUE TITLE
Scrolling on bucket produced 500 errors

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/SwiftRiver#192]
I'm seeing internal server errors in Firebug when I scroll around on a bucket. For what it's worth, there are currently on six drops in the bucket so all items are loaded (not sure if that has anything to do with it).

Bucket: https://swiftriver.io/brianherbert/bucket/korean-food/photos

<a href="http://cl.ly/392o2y0F1k1x2t0O1L3r"><img src="http://f.cl.ly/items/0g1L0M142g2m283r0F0u/Screen%20Shot%202012-06-22%20at%203.17.04%20PM.png" /></a>

**Comment by nlewis2142** [comment]
I have a bucket with 6 drops as well. I don't get a 500 error, but I do get a 404 from

```
//Throw a 404 if a non existent page is requested
if (($page > 1 OR $drop_id) AND empty($droplets))
{
    throw new HTTP_Exception_404(
        'The requested page :page was not found on this server.',
        array(':page' => $page)
        );
}
```

Of course, that 404 was intentional. Generally 500 errors stem from PHP errors. If that's the case, it's likely that one of the variables did not receive correct input.

**Comment by 69mb** [comment]
swiftriver.io specific issue. Error handling was turned off so all exceptions were error 500s. e373f6a sorted this out by allowing a prod specific environment for error handling.
