### ISSUE TITLE
Show user images in user search listing

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/SwiftRiver#193]
Currently a search for "Henry" returns Henry Addo with no photo. It would be nice to have the user image along with the name.

https://swiftriver.io/search/users?q=Henry

<a href="http://cl.ly/3H1e1a3N3X3m153k1F0i"><img src="http://f.cl.ly/items/0m2q3G45201c0w0X462k/Screen%20Shot%202012-06-22%20at%203.22.00%20PM.png" /></a>

**Comment by nlewis2142** [comment]
Can we display their nickname too? Possibly github-style.

`<nickname> (<real name in grey>)`
