### ISSUE TITLE
Thumbs up box CSS height incorrect

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/SwiftRiver#195]
<a href="http://cl.ly/0H1q1D1V2L1n2n0P0p0z"><img src="http://f.cl.ly/items/03190d2r2V0Y2H3v3e0s/Screen%20Shot%202012-06-22%20at%203.24.58%20PM.png" /></a>

<a href="http://cl.ly/0e1g313k421D382N0A1f"><img src="http://f.cl.ly/items/3O3K3O203T3Q1T061X43/Screen%20Shot%202012-06-22%20at%203.28.36%20PM.png" /></a>

The green box should fill the space behind the thumbs up icon.

**Comment by nlewis2142** [comment]
Duplicate of issue #176

**Comment by brianherbert** [comment]
Oppse, closing. Thanks :)
