### ISSUE TITLE
Flash Messages

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#20]
UI needs a way to flash a message to the user when an action is completed successfully/failed as feedback.

**Comment by dkobia** [comment]
Standard UI elements have been built already for displaying ERROR, SUCCESS and INFO messages... Just need to be implemented. Example: See login.

**Comment by 69mb** [comment]
Closed by bc898cc44ccfcf6bb8392c347fab2a37646202e2
