### ISSUE TITLE
Internal Messaging?

### ISSUE THREAD

**Issue by dkobia** [ushahidi/SwiftRiver#203]
With more users coming on board, I'm realizing that it'd be really useful ping/message another user. I'm wondering if it'd be useful at all to allow people to send each other messages within the system? We can't see other users contact information and have no way of contacting them at the moment.

**Comment by nlewis2142** [comment]
@dkobia
Code isn't quite clean enough to push at the moment, but a lot of the functionality is there now (Will make a branch + pull request once I get closer), Still need to refine and make more efficient as well as planning to add a feature to show recent (or unread) messages on the dashboard and somehow sync with the notification feature that can show new notifications at the top. A few screenshots of so far though are below. I'm pretty sure @brandonrosage will redo the looks on these, but I tried to make them look 'decent' for now.

The summaries in the inbox work similar to gmail showing the first portion of the message (or all of it if it's short enough).

<a href="https://picasaweb.google.com/lh/photo/itINg_Kr78Y7xTdKr5OZJcjBVG_0f5B7oOHmZugTIg0?feat=embedwebsite"><img src="https://lh5.googleusercontent.com/-aguVtkdR9F8/T_16kYwSpbI/AAAAAAAAAEc/FOLwO1gFkNE/s800/1342012049289.png" width="800" /></a>
<a href="https://picasaweb.google.com/lh/photo/C5P4G7JPdKZbabMEtpbv5sjBVG_0f5B7oOHmZugTIg0?feat=embedwebsite"><img src="https://lh5.googleusercontent.com/-wJMZdBPofmE/T_18xOb_73I/AAAAAAAAAEk/Poeln_rlRP0/s800/1342012610831.png" width="800" /></a>
<a href="https://picasaweb.google.com/lh/photo/UJm_VKAkVugU0W_Wo024ycjBVG_0f5B7oOHmZugTIg0?feat=embedwebsite"><img src="https://lh5.googleusercontent.com/-wpk7VoOjKBo/T_1-c3C8yCI/AAAAAAAAAEs/wTMDFO-a3B8/s800/1342013042248.png" width="800" /></a>

**Comment by nlewis2142** [comment]
Got a bit farther, almost ready for a commit + pull request after cleanup
- Changed the background color on the first two images to be more blue-ish and match the color scheme.
- Added timestamp to message details view
- Changed < 60 seconds to 'just now'
- Added dashboard view for up to 5 most-recent messages (shows unread/read status) -- or an empty message if none exist

<a href="https://picasaweb.google.com/lh/photo/RTlU48Iv2LGCOVWjOAPVQMjBVG_0f5B7oOHmZugTIg0?feat=embedwebsite"><img src="https://lh5.googleusercontent.com/-xf4Izk011h4/T_69vprctLI/AAAAAAAAAE4/Ix1YbSsQLRs/s800/1342094780624.png" /></a>

**Comment by ekala** [comment]
Already implemented - see the discussion log (for this issue) for details on the pull request that closed out this feature request.

Closing.
