### ISSUE TITLE
Obscure button to delete a river

### ISSUE THREAD

**Issue by nlewis2142** [ushahidi/SwiftRiver#205]
Either there is no button currently in the views or it is well hidden. Functionality for deleting a river looks like it already exists, but there is no interface for it or a way for normal users to access it.

**Comment by ekala** [comment]
The button actually exists but it's only accessible from the rivers listing page - http://deploymenturl/<account>/(rivers|buckets)

Clicking on the "Rivers" header for the Rivers listing/widget located in the right section of the dashboard should lead you to this page. I however do agree that this is not well surfaced in the application.

**Comment by nlewis2142** [comment]
Because I have the modal popup when getting to a river or bucket, I practically never (can't remember the last time) visit that page.

**Comment by dkobia** [comment]
Ideally this should be a big button instead of being buried under menus. We should encourage users to delete rivers when they're done with them. @brandonrosage?

**Comment by ekala** [comment]
Changing the tag to "Enhancement"

**Comment by heatherleson** [comment]
There is no way to easily delete a river or a bucket. I would like to remove them from the main search screens and from my swiftapp.  I disagree that this is an "enhancement", as it is more basic functionality. I can 'remove channels' but cannot remove the searches for river/buckets.

**Comment by brandonrosage** [comment]
[I've submitted my work in the "ui-dev" branch](https://github.com/ushahidi/SwiftRiver/commit/2e82eb74ffc01f06488b4a1215cf2356a8d53ba6) that addresses this issue by adding two more pathways for deleting rivers and buckets:
- The Rivers and Buckets modal windows triggered from the global header.
- Rivers' and Buckets' individual Settings > Options view.

This frontend code is integrated in both the /markup templates and the /views application code.

**Comment by Nhorning** [comment]
Hey there.  I'm trying to use swiftapp to help filter the feeds in my Ushahidi deployment, I've just been informed that I can't create anymore rivers, and it seems that now I can't delete any either.  I agree with heather that this is not an "enhancement" It's basic functionality it needs to be fixed in swiftapp ASAP.

**Comment by Nhorning** [comment]
I've managed to delete a river by entering the address indicated above manually.  This should be considered a work around to the "bug" which is logged.   One has to come to Github to log a bug before they find out how to delete a river.

**Comment by ekala** [comment]
@Nhorning, see the issue referenced in the preceding discussion above

Closing.
