### ISSUE TITLE
Swiftriver.io: Query error on search

### ISSUE THREAD

**Issue by nlewis2142** [ushahidi/SwiftRiver#207]
Got an error when I clicked search from the dashboard, typed in 'anything' (w/o quotes) and hit enter. Took a long time to load.

URL: https://swiftriver.io/search?q=anything
<img src="https://lh6.googleusercontent.com/-KSgM5qJVWFY/T_FbXO5IQLI/AAAAAAAAAC4/ISGfC2l3a3g/s708/1341217625936.png" />
<img src="https://lh6.googleusercontent.com/-v92rlnJA7ho/T_FcibQzrnI/AAAAAAAAADA/MR6VG-28cZU/s720/1341217927170.png" />

```
Incorrect key file for table '/tmp/#sql_3af3_0.MYI'; try to repair it [ SELECT `droplets`.`id` AS `id`, UNIX_TIMESTAMP(droplets.droplet_date_add) AS `sort_id`, `droplet_title`, `droplet_content`, `droplets`.`channel`, `identity_name`, `identity_avatar`, DATE_FORMAT(droplet_date_pub, "%b %e, %Y %H:%i UTC") AS `droplet_date_pub`, SUM(all_scores.score) AS `scores`, `user_scores`.`score` AS `user_score` FROM `droplets` JOIN `identities` ON (`droplets`.`identity_id` = `identities`.`id`) LEFT JOIN `droplet_scores` AS `all_scores` ON (`all_scores`.`droplet_id` = `droplets`.`id`) LEFT JOIN `droplet_scores` AS `user_scores` ON (`user_scores`.`droplet_id` = droplets.id AND user_scores.user_id = 35) WHERE `droplets`.`processing_status` = 255 AND `droplets`.`parent_id` = 0 GROUP BY `droplets`.`id` ORDER BY `droplets`.`droplet_date_add` DESC LIMIT 20 OFFSET 0 ]
```

**Comment by 69mb** [comment]
Search needs improvement in general and we have to implement Apache Solr or some other indexing service for swift river.io at the very least least. 

This particular query is running out of temp space doing an aggregation of the entire drops table.

**Comment by ekala** [comment]
Search is now handled by the API. For more info see: https://github.com/ushahidi/SwiftRiver-API/issues?milestone=1
