### ISSUE TITLE
Deadriver

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/SwiftRiver#209]
I set up the OSCON river in preparation for OSCON. The river http://imgur.com/kbUMQ stops at Friday last. There is no way to refresh or renew content in the SR dashboard if I want to keep using the river for longer projects. and, I receive no notice via email to renew my river or a notice on SR that the river is now complete.

How can I use it again? Do I have to delete and start over? Or, ask for you to reboot it? 

Thanks

Heather

**Comment by ekala** [comment]
By default, the app sends out a notification 3 days before a river expires.

Could you please check the spam folder? I'll also take a dive under the hood

**Comment by 69mb** [comment]
This was a db issue with swiftriver.io that's sorted now and its moving but users will get notifications once river expiry is turned on.
