### ISSUE TITLE
SMS Channel

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#219]
Create sn SMS plugin that integrates SMSSync and Clickatell.
- Text messages are private and rivers/buckets that contain sms channels and messages must be private.

**Comment by ekala** [comment]
SMS plugin with endpoints for SMSync, FrontlineSMS, Clickatell & Twilio implemented here: https://github.com/ushahidi/swiftriver-plugin-sms

Have the plugins been tested with said services? Pinging @dkobia for confirmation before closing.

**Comment by ekala** [comment]
Closing.
