### ISSUE TITLE
RedisException

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#224]
Investigate this intermittent error:

`redisent\RedisException [ 0 ]: invalid server response: e";s:5:"image";s:10:"thumbnails";a:1:{i:200;s:122:"http://c345203.r3.cf1.rackcdn.com/35b66631f70290882184c39aeb57e7b5_fashion-fail-poorly-dressed-who-wants-some-beefcake.jpg";}}}s:13:"droplet_image";a:3:{s:2:"id";s:5:"11075";s:3:"url";s:99:"http://failblog.files.wordpress.com/2012/05/fashion-fail-poorly-dressed-who-wants-some-beefcake.jpg";s:10:"thumbnails";a:1:{i:200;s:122:"http://c345203.r3.cf1.rackcdn.com/35b66631f70290882184c39aeb57e7b5_fashion-fail-poorly-dressed-who-wants-some-beefcake.jpg";}}s:6:"pl ~ MODPATH/K3-Cache_Redis/vendor/redisent/redisent.php [ 143 ]`

**Comment by heatherleson** [comment]
Encountered this on Day of Swift
1. action : added brandon as a collaborator and clicked the back button: https://swiftapp.com/ekala/bucket/community-dev-outreach
   -message: redisent\RedisException [ 0 ]: invalid server response: name_canonical";s:2:"uk";}}}}} ~ MODPATH/K3-Cache_Redis/vendor/redisent/redisent.php [ 143 ]
2. action: got this when I clicked list after looking at photo https://swiftapp.com/ehersman/river/illustrations/list
   -message: redisent\RedisException [ 0 ]: invalid server response: mage";s:10:"thumbnails";a:1:{i:200;s:104:"https://c345203.ssl.cf1.rackcdn.com/74c168d53d259be6a3ff8e12b5d24c72055997ab444f7f297cdde50e1d11570a.jpg";}}i:12;a:4:{s:2:"id";s:6:"920301";s:3:"url";s:99:"http://behance.vo.llnwd.net/profiles24/339627/projects/2204730/29da9ca58dd198d897f24e4fd08ff560.jpg";s:4:"type";s:5:"image";s:10:"thumbnails";a:1:{i:200;s:104:"https://c345203.ssl.cf1.rackcdn.com/a38b8ba5f51187da86ee237fccefb7377fbf2d69104d44ed500b68df737aac2b.jpg";}}i:13;a:4:{s:2:"id";s:6:"920302";s:3:"url";s:9 ~ MODPATH/K3-Cache_Redis/vendor/redisent/redisent.php [ 143 ]

**Comment by 69mb** [comment]
Updating redisent to the latest version appears to have resolved this.
