### ISSUE TITLE
Is there a deployment guide somewhere?

### ISSUE THREAD

**Issue by znmeb** [ushahidi/SwiftRiver#230]
Assume I have a Linux system. I've installed Apache, MySQL and PHP and all the requirements documented in README.md. And I've cloned the SwiftRiver repository. What do I do next? I want to start up a working instance of SwiftRiver on my workstation. Is there a "Getting Started" guide for that?

**Comment by dan-king** [comment]
Ditto. Our team is also trying to install SwiftRiver locally but running into problems and could use a "Getting Started" guide. Super big bonus would be a video tutorial walking through the installation process from scratch.
