### ISSUE TITLE
Plugin Settings Hook

### ISSUE THREAD

**Issue by dkobia** [ushahidi/SwiftRiver#238]
Currently wrestling with where to place a hook for plugins settings. Some plugins have updateable entries (settings table).
- Add a hook to add options to the applications settings?
- Or a new menu?
- Or perhaps even a 'settings' link that allows the plugin to create a totally new view?

![](http://dl.dropbox.com/u/501659/Screenshots/mss06352~kof.png)

@69mb, @brandonrosage, @ekala, @Deathshiver?

**Comment by dan-king** [comment]
Is this a special developer-only setting? I don't see a link to "Site Settings" on my dashboard. https://swiftapp.com/dan-king

**Comment by dkobia** [comment]
@dan-king ... its viewable only by the administrator, not the site users for basic site settings as you can see in the screenshot. You should be able to see this if you have it set up on your local.

**Comment by ekala** [comment]
I think the settings hook should introduce a settings link/button in the plugins listing page a la:
![Plugin Settings](https://dl.dropbox.com/u/2635815/plugin-settings.png)

Clicking on the button would then bring up a dialog where the administrator can provide the settings parameters for the plugin.
