### ISSUE TITLE
Installation Issue - Chrome never prompts for current password

### ISSUE THREAD

**Issue by dan-king** [ushahidi/SwiftRiver#244]
Browser: Chrome 21.0.1180.79

Never prompted for current password.  Just get a red box with "Uh oh.  Current password is incorrect"

**Comment by dan-king** [comment]
Hi Emmanuel,

Apologies for the delay.

Nate encountered "Chrome never prompts for current password (#244)" on the
local install. 

Thanks,

Dan

-----Original Message-----

**Comment by ekala** [comment]
@dan-king This issue appears to have been resolved. See screenie below:

![Chrome Password Prompt](http://f.cl.ly/items/1T3y1r001233100V2y2T/password-prompt.png)

Closing.
