### ISSUE TITLE
Propagation Delay

### ISSUE THREAD

**Issue by dan-king** [ushahidi/SwiftRiver#247]
There is a delay from the time a river is setup to when it begins to collect drops.

I set up "Syria Test River" with twitter keyword #syria. After 60 minutes there were several hundred tweets but no drops, despite clicking the "refresh manually" link.

See https://swiftapp.com/dan-king/river/syria-test-river/list

**Comment by heatherleson** [comment]
Day of Swift update- Emmanuel advised that there was a production delay. New rivers were not updating in the stated up to 60 minutes. Created - https://swiftapp.com/heather/river/kabul/list  and https://swiftapp.com/heather/river/tiff/list at 06:45 am EDT. It is 15:00 EDT and the rivers did not flow.

**Comment by 69mb** [comment]
swiftapp.com specific issue that has has since been resolved.
