### ISSUE TITLE
Total number of drops in a river.

### ISSUE THREAD

**Issue by dan-king** [ushahidi/SwiftRiver#250]
It would be nice if the "list" and "drop" pages showed the grand total number of drops currently in the river.

**Comment by 69mb** [comment]
Drop count is already cached in the rivers table so there is no harm is displaying this... @brandonrosage

**Comment by brandonrosage** [comment]
I've added the drop total to river and bucket views [in the latest "ui dev" commit](https://github.com/ushahidi/SwiftRiver/commit/629f662d8b55296e55df96c5dae190f970554319). It's [appended to the name of the active view](http://cl.ly/image/1y1i192a3s31) in the river or bucket's view menu.

[I've added the frontend markup to the application code](https://github.com/ushahidi/SwiftRiver/blob/ui-dev/themes/default/views/pages/river/layout.php#L33), commented out until the proper conditionals are attached.

**Comment by ekala** [comment]
@dan-king This will be included in the build out of the new UI prototype.

**Comment by ekala** [comment]
Implemented. There are two places that drop count is shown:
- In the **Content** tab on the user dashboard
- In the river/bucket view - this shows the no. of drops currently in view and the counter is updated as more drops get added to the view
