### ISSUE TITLE
River creation - notification and missing river

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/SwiftRiver#265]
I attempted to set up a new river - quebec elections 2012. I added the description and clicked 'next'. There was no river notice for the creation. So, I logged out and logged back in.  I attempted to create the river, but it says it exists. http://imgur.com/lxHaR

I checked my river dropdown and it does not: http://imgur.com/jYsCu
I clicked rivers( top right hand corner button), I clicked dashboard and i looked in the right hand panel bar. Not there. So I searched "quebec" and nothing came up

This was going to be a simulation test for the Quebec elections tomorrow.

**Comment by 69mb** [comment]
db issue at swiftapp.com was causing this which has since been resolved.
