### ISSUE TITLE
River still pulling keyword after it was removed

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/SwiftRiver#272]
When I created this river: https://swiftapp.com/rjmackay/river/peace-tracker
I added the twitter keyword "peace"
I later changed this to "#peace" as the original keyword was pulling too much junk. However it seems to still be pulling the original keyword.
Is there something else going on here? or is this a bug?

**Comment by 69mb** [comment]
Yeah this is a bug, we were inadvertently stripping out the '#' from keywords but this should now be ok.
