### ISSUE TITLE
Bucket Discussion

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#28]
Ability to have discussions around a bucket.

UI for this is required to proceed.

**Comment by brandonrosage** [comment]
This is staged on swiftly.ushahididev.com, pending your approval for commit. (https://ushahidi.basecamphq.com/projects/8944360-swiftriver/posts/57924149/comments)

**Comment by brandonrosage** [comment]
The following commit addresses this: https://github.com/ushahidi/Swiftriver_v2/commit/4af47feb27af80ce2825db139d4df17c99e44e7e

**Comment by ekala** [comment]
@dkobia offered to take this up

**Comment by dkobia** [comment]
Forgot to #ref this issue from 3c20bb183ba8d6fb91bc01fe4210b0232790c6de. Will #ref and close with next commit.
