### ISSUE TITLE
Output of rivers and buckets as rss

### ISSUE THREAD

**Issue by Nhorning** [ushahidi/SwiftRiver#288]
As it is now, each river and bucket has a little rss icon attached to it. Clicking on this icon will take one to a "create email id" interface.  I have no idea what to do with this e-mail ID.   Perhaps its explained somewhere,  but if I don't know what to do with it when I see it, that's an interface issue.  

However, what would be better is if it was possible to just create an RSS feed based on the river and or bucket, somewhat like the functionality in Yahoo Pipes.

**Comment by 69mb** [comment]
Fixed on swiftapp.com and now the rss icons link to a feed.

The email id on swiftapp.com is an email channel into you river and mail sent to that address are added as drops. The river's email address can be found in the settings page:

![](https://gist.github.com/raw/f28ceade9732895ad1d9/0574afcdaf33098ed8deeb0f94fe3c8ef618b490/fxrG4AlHH4PBHVHm.png)

**Comment by Nhorning** [comment]
Thanks!  this is great to Know!   I think this I can finally make swiftriver useful for my ushahidi deployment.  
For instance, I might be able to take a UN sitrep in through the e-mail ID, feed it into Yahoo pipes, use a custom pipe to break it down into individual items, and then feed that back into a river!   

More simply: I can also make custom filters on my river of RSS and feed those into my deployment as thematic feeds!

**Comment by Nhorning** [comment]
Ok.  The feed I just created won't import into feedburner, Ushahidi, or Google reader.   Please confirm on your end, and if it works for you I'll give you more specific information about my errors.

**Comment by Nhorning** [comment]
Well... Now it's working.  Maybe you fixed it?  Maybe it just took some time?

**Comment by 69mb** [comment]
Still in the process of fixing it but #224 seems to be the main contributor to this problem.

**Comment by Nhorning** [comment]
I don't think that's the error that I got.  I don't have it available to post anymore, but I'll put it here if I get it again.
