### ISSUE TITLE
E-mails to river e-mail ID bounce.  

### ISSUE THREAD

**Issue by Nhorning** [ushahidi/SwiftRiver#294]
Please see the error below.  Is there anything I am supposed to do besides mail to the address indicated in the river settings? 

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  395YIcyo2Vd@rivers.swiftapp.com
    The mail server could not deliver mail to 395yicyo2vd@rivers.swiftapp.com.  The account or domain may not exist, they may be blacklisted, or missing the proper dns entries.

------ This is a copy of the message, including all the headers. ------

Return-path: ictsupport@pbi-nepal.org
Received: from [27.34.55.16](port=38485 helo=[192.168.11.19])
    by picasso.ekonnic.org with esmtpsa (TLSv1:DHE-RSA-AES256-SHA:256)
    (Exim 4.80)
    (envelope-from ictsupport@pbi-nepal.org)
    id 1TSncY-0003dd-Co
    for 395YIcyo2Vd@rivers.swiftapp.com; Mon, 29 Oct 2012 11:35:07 +0000
Message-ID: 508E69E7.6040706@pbi-nepal.org
Date: Mon, 29 Oct 2012 17:20:03 +0545
From: Neil Horning ictsupport@pbi-nepal.org
Organization: PBI
User-Agent: Mozilla/5.0 (X11; Linux i686; rv:15.0) Gecko/20120912 Thunderbird/15.0.1
MIME-Version: 1.0
To: 395YIcyo2Vd@rivers.swiftapp.com
Subject: test for river
Content-Type: multipart/alternative;
 boundary="------------060703020600050005040609"
X-PBI-MailScanner-Information: Please contact the ISP for more information
X-PBI-MailScanner-ID: 1TSncY-0003dd-Co
X-PBI-MailScanner: Found to be clean
X-PBI-MailScanner-SpamCheck: not spam, SpamAssassin (not cached,
    score=-2.899, required 1, autolearn=not spam, ALL_TRUSTED -1.00,
    BAYES_00 -1.90, HTML_MESSAGE 0.00)
X-PBI-MailScanner-From: ictsupport@pbi-nepal.org
X-PBI-MailScanner-Watermark: 1352115312.43751@qRfiw6U2nN26JYUTxZJs5g
X-Spam-Status: No

This is a multi-part message in MIME format.
--------------060703020600050005040609
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: 7bit

---
- *

A.     NATIONAL UPDATES

Over 150 former Constituent Assembly members representing around two dozen political parties spoke in favor of reinstating the dissolved Constitutio nal Assembly during their gathering on Thursday.

11 Oct: Public Service Commission has scrapped the tests taken by two examinees after finding that their close kin were among the question paper moderators and examiners.

B.      GENERAL UPDATE

I.       < /b>Highways/Roads / Traffic:  vehicular movement operating in the major roads and highways across the country.

II.    Ferry service has been halted at Sunkoshi River in Jayaramghat, Khotang district, Leguwaghat of Dhankuta. Vehicle movement towards Khotang, Okhaldhunga and Solukhumbu districts has been obstructed. 

III.    Market/Institutions/Industries- are open across the country.

 -----Truncated-----

**Comment by 69mb** [comment]
Looks ok from my end and I've sent a couple test messages. 

The bounce message isn't from our mail servers... any chance you could check on yours to see why specifically the mail is bouncing there?

**Comment by Nhorning** [comment]
I can mail through gmail, so there is a work around  for this, by forwarding mails through a dummy gmail account first.  It's possible there is an issue with my ISP blacklisting IP's that shouldn't be blacklisted. We've had some problems with IP blacklisting that keep me from logging on to my deployment.  I'll keep you updated if something like this happens with a different e-mail service.
