### ISSUE TITLE
ErrorException [ Fatal Error ]: Class 'Database_Mysql' not found

### ISSUE THREAD

**Issue by vahal** [ushahidi/SwiftRiver#311]
MODPATH/database/classes/Kohana/Database.php [ 78 ]

PHP 5.3.10-1ubuntu3.4
APACHE 2.2.22
MYSQL 5.5.28-0ubuntu0.12.04.3

I have installed extensions and tried to keep readme.md

**Comment by laurent22** [comment]
In your database config file, change the type from "mysql" to "MySQL". This is because the name of the database driver has changed in Kohana 3.

**Comment by vahal** [comment]
Thanks a lot... Greetings from Parish of St. Lawrence

**Comment by ekala** [comment]
Thanks @laurent22  :+1:!

Closing.

**Comment by almirsarajcic** [comment]
Wow, great.
Thanks.
(Google brought me here.)

**Comment by ibrhim123** [comment]
thnaks @aurent22 u saved much of mine time
