### ISSUE TITLE
Unable to clone the master repo

### ISSUE THREAD

**Issue by arcotbha** [ushahidi/SwiftRiver#325]
Hi I've been getting this error when I try to clone the master repo. 

Submodule 'modules/purifier' (git://github.com/shadowhand/purifier.git) register
ed for path 'modules/purifier'
Submodule 'modules/unittest' (git://github.com/kohana/unittest.git) registered f
or path 'modules/unittest'
Submodule 'plugins/email' (git://github.com/ushahidi/swiftriver-plugin-email.git
) registered for path 'plugins/email'
Submodule 'plugins/feedwriter' (git://github.com/ushahidi/swiftriver-plugin-feed
writer.git) registered for path 'plugins/feedwriter'
Submodule 'plugins/mediaextractor' (git://github.com/ushahidi/swiftriver-plugin-
mediaextractor.git) registered for path 'plugins/mediaextractor'
Submodule 'plugins/rss' (git://github.com/ushahidi/swiftriver-plugin-rss.git) re
gistered for path 'plugins/rss'
Submodule 'plugins/swiftcore' (git://github.com/ushahidi/swiftriver-plugin-swift
core.git) registered for path 'plugins/swiftcore'
Submodule 'plugins/twitter' (git://github.com/ushahidi/swiftriver-plugin-twitter
.git) registered for path 'plugins/twitter'
Submodule 'system' (https://github.com/kohana/core.git) registered for path 'sys
tem'
Cloning into 'modules/auth'...
remote: Counting objects: 748, done.
remote: Compressing objects: 100% (535/535), done.
remote: Total 748 (delta 227), reused 673 (delta 164)
Receiving objects: 100% (748/748), 97.80 KiB, done.
Resolving deltas: 100% (227/227), done.
error: refs/remotes/origin/3.0/master does not point to a valid object!
error: refs/remotes/origin/3.1/master does not point to a valid object!
error: refs/remotes/origin/3.2/develop does not point to a valid object!
error: refs/remotes/origin/3.2/feature/CS-Cleanup does not point to a valid obje
ct!
error: refs/remotes/origin/3.2/master does not point to a valid object!
error: refs/remotes/origin/3.3/develop does not point to a valid object!
error: refs/remotes/origin/3.3/master does not point to a valid object!
error: refs/remotes/origin/3.4/develop does not point to a valid object!
error: refs/tags/3.0.6 does not point to a valid object!
error: refs/tags/3.0.6.1 does not point to a valid object!
error: refs/tags/3.0.6.2 does not point to a valid object!
error: refs/tags/3.0.7 does not point to a valid object!
error: refs/tags/3.0.8 does not point to a valid object!
error: refs/tags/3.0.9 does not point to a valid object!
error: refs/tags/v3.0.10 does not point to a valid object!
error: refs/tags/v3.0.11 does not point to a valid object!
error: refs/tags/v3.0.12 does not point to a valid object!
error: refs/tags/v3.1.0 does not point to a valid object!
error: refs/tags/v3.1.1 does not point to a valid object!
error: refs/tags/v3.1.2 does not point to a valid object!
error: refs/tags/v3.1.3 does not point to a valid object!
error: refs/tags/v3.1.4 does not point to a valid object!
error: refs/tags/v3.1.5 does not point to a valid object!
error: refs/tags/v3.2.0 does not point to a valid object!
error: refs/tags/v3.2.0-RC1 does not point to a valid object!
error: refs/tags/v3.2.0-RC2 does not point to a valid object!
error: refs/tags/v3.2.1 does not point to a valid object!
error: refs/tags/v3.2.2 does not point to a valid object!
error: refs/tags/v3.3.0 does not point to a valid object!
error: Trying to write ref refs/heads/3.3/develop with nonexistent object 74f299
51da75a3d665e9468b8c54768f917bb7c1
fatal: Cannot update the ref 'HEAD'.
Clone of 'git://github.com/kohana/auth.git' into submodule path 'modules/auth' f
ailed

**Comment by uofarepo** [comment]
I tried to clone the master repo I got this error, Am new to using git don't know how to proceed. 

Submodule 'system' (https://github.com/kohana/core.git) registered for path 'system'
Cloning into 'modules/auth'...
fatal: unable to connect to github.com:
github.com[0: 207.97.227.239]: errno=Connection timed out

Clone of 'git://github.com/kohana/auth.git' into submodule path 'modules/auth' failed

Please help am completely new to git and I don't know how to proceed on this.
