### ISSUE TITLE
ability to delete rivers and buckets

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/SwiftRiver#333]
There is no ability to delete or archive rivers and buckets.

This request was provided in February. Unable to locate open issue (re-adding)

**Comment by ekala** [comment]
Fixed in the new UI prototype build out. Users can now do this from their dashboard.

See: ![Delete rivers and buckets](https://dl.dropbox.com/u/2635815/Screenshots/-kbh7ljyku0g.png)

This will be rolled out to production within the next 2 weeks

Closing.

**Comment by heatherleson** [comment]
cheers!
