### ISSUE TITLE
Kohana throws error after changing the name of a River or Bucket.

### ISSUE THREAD

**Issue by dan-king** [ushahidi/SwiftRiver#359]
After changing the name of a River or Bucket Kohana throws an error: 

Kohana_HTTP_Exception [ 404 ]: Unable to find a route to match the URI: swiftriver/admin/bucket/bucket-name-here/settings
APPPATH/classes/Request.php [ 77 ]
72 
73      if ( ! $this->_route instanceof Route)
74      {
75          return HTTP_Exception::factory(404, 'Unable to find a route to match the URI: :uri', array(
76              ':uri' => $this->_uri,
77          ))->request($this)
78              ->get_response();
79      }
80 
81      if ( ! $this->_client instanceof Request_Client)
82      {

The name does get changed, it just throws an unpleasant looking error message.

![kohana error after changing name of river or bucket](https://f.cloud.github.com/assets/2077370/733571/62fc49ee-e2a1-11e2-9844-907a05633e70.png)

**Comment by ekala** [comment]
Hi @dan-king,
This has been fixed in the last UI & API codebases. Error handling and reporting has also been revised so that users don't get presented with the exception stack trace.

Please update your installation and re-open if the issue resurfaces.

Thanks.
