### ISSUE TITLE
Drops Link Disappears When More Link Clicked

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#46]
Drops/More tab issues: Exists http://i.imgur.com/c9lk4.jpg, but when you click on more, "Drops" disappears, even when you hover on it http://i.imgur.com/XxN97.jpg.
Brandon, we're assuming this is done on purpose to close/open the sub-menu.  Is this the best way to handle this?

**Comment by ekala** [comment]
No longer relevant since the UI has been reworked and wired in. Closing.
