### ISSUE TITLE
Implement the Droplet Meter

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#47]
Just do it

**Comment by ekala** [comment]
Last I checked, we elected to implement the droplet meter only when the filters are active. However, some filters may yield a 0.00000x% match in which case the display shall still be distorted - for such scenarios, I don't it's worth displaying the meter...

**Comment by ekala** [comment]
Droplet meter appears to have been purged in the UI rework. Open a new issue if this crops up as a feature later on
