### ISSUE TITLE
Collaboration Levels

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#48]
Create a 'reader' access level in addition to the 'editor' level.
- Editors can add collaborators and change settings of the river/bucket
- Reader can only see the bucket/river but not change its settings.

**Comment by ekala** [comment]
Is this relevant for an MVP? @brandonrosage @dkobia

**Comment by 69mb** [comment]
Yeah it is. The issue is that for a private river/bucket, how do I grant access to others without allowing them to change settings?

Greatest stumbling block for me earlier was how to fit this into the UI but now with the pattern portfolio, it is easier to put something together that fits in consistently.
