### ISSUE TITLE
Interchange Droplet Title and Summary in Droplet Summary View

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#49]
- Why does the title of the website, not the title of the post/article, show up in big bold letters.  Seems this should be reversed: http://dl.dropbox.com/u/450917/Screenshots/0c.png
- When it comes from a Twitter handle or a website, those links should be active.

**Comment by ekala** [comment]
Closed by 19fc0ddecd70bc39551573535638eb870ced72a9
