### ISSUE TITLE
Remove Teams

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#54]
- What are "Teams"?  How do I activate it?
- I asked it to delete "Team 2" and nothing happened.
- I tried to create a new team, and nothing happened.
- On "teams" when I click "filter", it takes me to the "River" sub-nav item.  No idea what this is for either.

**\* REMOVE TEAMS FOR NOW ***

**Comment by ekala** [comment]
Closed by 93484d716bf8caea4154502ffa8116ac30d47f00
