### ISSUE TITLE
View more droplets feature -- move populating to top?

### ISSUE THREAD

**Issue by dkobia** [ushahidi/SwiftRiver#6]
I think we need to move the 'view more' button to the top? And have new droplets populate from the top instead of the bottom? Thoughts?

**Comment by 69mb** [comment]
You mean viewin page by page instead of the infinite scroll with new
pages replacing the previous in the dom via JavaScript?

## 

Brian

On 15 Dec 2011, at 07:14 PM, David Kobia
reply@reply.github.com
wrote:

**Comment by dkobia** [comment]
Not page by page... Just having the button to view more at the top, and populate new items on top. Paging is counter intuitive too for droplet streaming and something we absolutely shouldn't use.

**Comment by ekala** [comment]
The river view is just that; New items at the top and older items always appearing downstream (i.e. via the kinetic/"infinite" scrolling). Also by "new" items, I presume we're referring to droplets that have just joined the river.

**Comment by 69mb** [comment]
Closed by 368f2ce8b083038f01e6054de0ac6c8bc2168637
