### ISSUE TITLE
Improve Channel Selection

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#66]
- Channel Selections are a little unclear. http://o7.no/xghJO4 -- I think the inactive channel should be a shade darker?
- Should auto turn "on" when I hit the + button or add text.
- RSS needs to be capitalized
- When applying filters paused to look for RSS feed to add and the page auto-applied stuff, it did not stay as I left it
- The text fields shouldn't be text fields anymore if they have been entered before, it's to

**Comment by ekala** [comment]
@brandonrosage Please help with the first bullet point? The other items have already been addressed by a series of commits.

**Comment by ekala** [comment]
Closed by e6a00379e81983cd34f856f318ac17cfbd40fb56
