### ISSUE TITLE
Show number of drops since last visit

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#68]
a la Tweetbot or Twitter web

**Comment by ekala** [comment]
Update the view with the no. of new items with an option for the user to allow them to trickle them into the display?
Currently, new items just appear on the display but there's no visual cue to notify the user that new content has streamed in.

Thoughts @dkobia @brandonrosage

**Comment by 69mb** [comment]
Twitter has this right --> http://dl.dropbox.com/u/48291217/Screenshots/zul5.png

If we could have the same ui, i.e. when the polling brings in new drops, they just accumulate with the count showing like in the screenshot and when the user clicks they are displayed.

@brandonrosage Doable in the new ui?

**Comment by brandonrosage** [comment]
Yep. I'll include it in the current build.

Brandon Rosage
Design and development
phone: 360-510-5860

**Comment by ekala** [comment]
This appears to have been addressed in the current build --> http://cl.ly/08363w0w0q1A2b3n2V1e

Closing this out.
