### ISSUE TITLE
Import Google Reader Feeds

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#74]
A way of importing feeds from existing services e.g. Google Reader so that users don't have to start from scratch.

**Comment by brianherbert** [comment]
An easy thing to implement might just be importing OPML files.

**Comment by ekala** [comment]
@brianherbert  Indeed - and that is the route we took. Additionally, there's on need to write code for a service that shall soon be dead.

Closing this out as OPML import (#76) has already been implemented.
