### ISSUE TITLE
Search Page

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#75]
Need a place to search for public users and rivers / a way to surface them. How to find rivers to collaborate on / users to collaborate with? Simple solution is a search page./Suggestions? Add this to discoverability+Findability

**Comment by 69mb** [comment]
See this is catered for in the new UI but the UI for how the results will be presented is pending.

![](http://dl.dropbox.com/u/48291217/Screenshots/g~ji.png)

**Comment by brandonrosage** [comment]
@69mb Yes. My intention is to stage a template that is nearly identical to a river's drops view, but with a custom page title to label it as a search results. Will update when it's prepped.

**Comment by brandonrosage** [comment]
Today's commit includes [a set of templates for search results](https://github.com/ushahidi/Swiftriver_v2/tree/refresh/markup/search). The templates are a series of results categories: [Drops](https://github.com/ushahidi/Swiftriver_v2/blob/refresh/markup/search/drops.php), [rivers](https://github.com/ushahidi/Swiftriver_v2/blob/refresh/markup/search/rivers.php), [buckets](https://github.com/ushahidi/Swiftriver_v2/blob/refresh/markup/search/buckets.php) and [users](https://github.com/ushahidi/Swiftriver_v2/blob/refresh/markup/search/users.php).

**Comment by 69mb** [comment]
- Search seems to be storing the query in a session, reusing that prevent further searches.
- Search page should not say "Search this river/ Search this bucket" while on the dashboard.
