### ISSUE TITLE
RSS Feed Items Out of Order

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/SwiftRiver#81]
RSS feed items look like they are being pulled in and sorted by time of entry into the database and not the content date. I added a number of RSS feeds and all of the items are showing up in chunks of each blog, not mixed by posting date. I see 2012 and 2011 dates all being mixed and not in any logical order.

**Comment by brianherbert** [comment]
Btw, the river I'm looking at is http://swiftly.ushahididev.com/river/index/32

**Comment by ekala** [comment]
Items ordered by the date when they were published not when they were added into the system. 

While the page is in view, newly fetched items trickle in at the top but they may not retain their position when the page is manually refreshed. This applies to cases where a newly added item has a publication date that is much older/earlier.

**Comment by 69mb** [comment]
Just some notes on how to fix this lest I forget:
- Droplet pagination in the list should be based on river_droplets.id and bucket_droplets.id and not droplets.id. This way, we are guaranteed that a higher id means a droplet entered a river/bucket later. 
- Adding of droplets to the list should not be a simple jquery prepend/append but droplets should be inserted in based on their dates in the view. Say there is a droplet for 23rd Feb and another for 25th Feb. if one for 24th feb comes in, it should be inserted between the droplets for 23rd and 25th in the DOM. This will involve adding a date comparator to the Droplets model and a reference to the view from the droplet.
