### ISSUE TITLE
Nav Dissapears When Nav Link Clicked

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/SwiftRiver#82]
When I click filter, the other nav items go away, but the areas where they were are still clickable.

<img src="http://dl.dropbox.com/u/1938726/Screenshots/jwm6.png" />
Screenshot: http://dl.dropbox.com/u/1938726/Screenshots/jwm6.png

Another example, when I click "more", the same thing happens.

<img src="http://dl.dropbox.com/u/1938726/Screenshots/805x.png" />
Screenshot: http://dl.dropbox.com/u/1938726/Screenshots/805x.png

**Comment by 69mb** [comment]
New ui removes panels so this is no longer an issue.
