### ISSUE TITLE
"oplets" above Droplets Meter Thing

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/SwiftRiver#83]
The thing at the top of the page that measures something (not sure what it's for) has a typo. "oplets" should be Droplets

<img src="http://dl.dropbox.com/u/1938726/Screenshots/8akq.png" />
Screenshot: http://dl.dropbox.com/u/1938726/Screenshots/8akq.png

**Comment by ekala** [comment]
The UI has been reworked and this feature has been retired - renders this bug moot. :muscle:

**Comment by brianherbert** [comment]
Good work, Kala!
