### ISSUE TITLE
Cursor Changes to Editable on Noneditable Title

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/SwiftRiver#84]
The title of my river doesn't do anything but lightly highlight when I mouse over. My mouse cursor indicates that I can click it and change it but clicking does nothing.

<img src="http://dl.dropbox.com/u/1938726/Screenshots/th1q.png" />
Screenshot: http://dl.dropbox.com/u/1938726/Screenshots/th1q.png

**Comment by ekala** [comment]
Ah, we initially had inline editing of river & bucket names but that doesn't seem to be the case anymore. Good old fashioned editing.

Tagging @brandonrosage on this one.
