### ISSUE TITLE
Duplicate Tag on a Droplet

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/SwiftRiver#85]
Looking at a feed item, I can see there are two identical tags, "Whitney Houston". I'm assuming there should only be one of each tag.

<img src="http://dl.dropbox.com/u/1938726/Screenshots/ft3n.png" />
Screenshot: http://dl.dropbox.com/u/1938726/Screenshots/ft3n.png

**Comment by ekala** [comment]
Fixed by 266ad977e94e7e1f88f9a9ec59f7b020bf16b0a8 and subsequent commits

Also cleaned up testdrive DB to purge duplicates.
