### ISSUE TITLE
Locations Pulled From Droplet Are Not Locations

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/SwiftRiver#86]
Looking at a droplet "Photosweeper: Take Charge of Your Photos and Free Up Disk Space" (sorry, not sure how to find the droplet's ID), Swift has parsed out locations that aren't locations.

<img src="http://dl.dropbox.com/u/1938726/Screenshots/_dkg.png" />
Screenshot: http://dl.dropbox.com/u/1938726/Screenshots/_dkg.png

**Comment by ekala** [comment]
This is an NLP issue. The semantic engine requires further training and additional tuning. Also, we're quickly learning that NLP systems are right about 80% of the time. Therefore, we will have outliers for sometime

**Comment by brianherbert** [comment]
Cool, I guess then we need some way to help train the system here. I'm sure you're working on it since I'm just now doing a deep dive. Perhaps a simple X to remove it from the list if it isn't a location and some way to add locations, like you can with tags.

**Comment by ekala** [comment]
Related to #22

**Comment by brianherbert** [comment]
FWIW, I'm seeing proper location data for a feed.

<img src="http://dl.dropbox.com/u/1938726/Screenshots/4q4u.png" />
Screenshot: http://dl.dropbox.com/u/1938726/Screenshots/4q4u.png

**Comment by ekala** [comment]
We have replaced the old semantic tagging API with one that has better semantic extraction capabilities. Closing this out.
