### ISSUE TITLE
Changing Bucket Settings to Public Reloads Different Page

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/SwiftRiver#88]
When I set my bucket to Public by hitting the radio button for "Public/Private", the page is reloaded to the "Drops" screen when I wasn't finished with my bucket settings. I should stay on the bucket settings page until I'm finished with settings.

**Comment by ekala** [comment]
This is actually deliberate...

**Comment by brianherbert** [comment]
There are other settings on the page and as I was scrolling, it felt like a really jarring experience. Maybe make it the last setting on the settings page if there's some reason it has to load a different page after selecting the privacy setting.
