### ISSUE TITLE
Add subscribe button on a river view

### ISSUE THREAD

**Issue by 69mb** [ushahidi/SwiftRiver#89]
Currently its only possible to subscribe to a river from a user's profile page. Also add a way to subscribe from the river/bucket page.

**Comment by brandonrosage** [comment]
[Today's second commit](https://github.com/ushahidi/Swiftriver_v2/commit/0adadf1f833c6efcb4b69339739e797506f1cae8) includes the follow button markup in the [river](https://github.com/ushahidi/Swiftriver_v2/blob/refresh/themes/default/views/pages/river/main.php#L22-26) and [bucket](https://github.com/ushahidi/Swiftriver_v2/blob/refresh/themes/default/views/pages/bucket/main.php#L33-37) views.
