### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by ekala** [ushahidi/SwiftRiver#90]
Bookmarks are a way of saving a user's last position in the stream/river. The bookmark can be created in two ways: automatically or manually. An automatic bookmark should be created each time the river/stream is updated with new drops. For manual bookmarks, we can utilize one of those floating widget thingamabobs with bookmark button in it.

Looping in @brandonrosage and @dkobia for additional thoughts.

Make sense?

**Comment by 69mb** [comment]
Basically the idea is I need a way to mark where I was in a river and the automatic buoy marks the pasition I was the last time I visited a River so the next time I visit it, and news droplets have come in, I can continue reading from where I was.

**Comment by dkobia** [comment]
Definitely a much needed feature. I've lost myself a few times. I suppose we're using **Buoy** to stick with the water theme i.e. instead of _Bookmark_?

**Comment by 69mb** [comment]
Not sure how I got assigned this one but need the ui to proceed. Ping @brandonrosage

**Comment by brandonrosage** [comment]
@69mb I'll sneak this into the UI's current "drops" view for rivers and pass this issue onto you when I've pushed the commit.

**Comment by 69mb** [comment]
Cool. Thanks.

**Comment by brandonrosage** [comment]
I've included the necessary markup in [today's commit](https://github.com/ushahidi/Swiftriver_v2/commit/0560a794377b88f3fe25e2e2e6a116415ea98318).

For a river's view to scroll to and highlight the buoyed drop, it simply requires the drop to have [the ID "buoy" assigned to its parent article element](https://github.com/ushahidi/Swiftriver_v2/blob/refresh/markup/river/index.php#L134). [The global.js](https://github.com/ushahidi/Swiftriver_v2/blob/refresh/themes/default/media/js/global.js#L174-180) finds it, scrolls to it, displays a brief "This is where you left off" message and highlights the drop.

**Comment by heatherleson** [comment]
I think we should still call these bookmarks. Buoy is confusing and would be hard to translate

**Comment by ekala** [comment]
Closed by pull request #208.

Closing.
