### ISSUE TITLE
Meta Content Links & Images

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/SwiftRiver#93]
I feel like the links listed under "Links" that are images (the last two in the following screenshot) should be thumbnails. If not listing thumbnails under links, perhaps there should be an "Images" meta content category.

<img src="http://dl.dropbox.com/u/1938726/Screenshots/4q4u.png" />
Screenshot: http://dl.dropbox.com/u/1938726/Screenshots/4q4u.png

**Comment by ekala** [comment]
Related to #19 therefore closed by eb7fc876853974272d53506deb2c28f89fb4f89f
