### ISSUE TITLE
Selecting Channel on River Does Nothing

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/SwiftRiver#95]
When I select a channel and click on "apply filters", nothing happens. I selected all, Twitter, Facebook and SMS. I should note that I don't have any of those channels in my river, just RSS, which isn't a selectable option.

<img src="http://dl.dropbox.com/u/1938726/Screenshots/aj1x.png" />
Screenshot: http://dl.dropbox.com/u/1938726/Screenshots/aj1x.png

**Comment by ekala** [comment]
Duplication of #2
