### ISSUE TITLE
Unclear what to do after creating a new River

### ISSUE THREAD

**Issue by dkobia** [ushahidi/SwiftRiver#99]
Currently when creating a new river the process is:
- Click 'create new'
- Name the River
- Save
- Redirected back to River
- **At this point its very unclear to a user that they're supposed to click 'River Settings' at top right to set up Channels**

**Comment by ekala** [comment]
I'm thinking the river creation process ought to be wizard-driven; hand hold the user through the process

Thoughts? @69mb @brandonrosage

**Comment by ekala** [comment]
Closing and merging with #118
